#!/bin/sh

# usage: source environment [optional: ios64, iossim, android-aarch64]
ARG=$1

if [[ -z "$ARG" ]]; then
    echo "setting compiler for desktop platforms";
elif [ "ios64" == "$ARG" ]; then
    echo "setting compiler for Apple iOS (only 64bit)";
elif [ "iossim" == "$ARG" ]; then
    echo "setting compiler for Apple iOS Simulator";
elif [ "android-aarch64" == "$ARG" ]; then
    echo "setting compiler for Android arm64-v8a";
else
    echo "no suitable platform found!"
    return 1
fi

# check Android env vars
if [ "android-*" == "$ARG" ]; then
    echo "checking env vars for Android";
    if [[ -z "$ANDROID_NDK" ]]; then
        echo "ANDROID_NDK not defined!"
        return 1
    fi
    if [[ -z "$ANDROID_HOST_TAG" ]]; then
        echo "ANDROID_HOST_TAG not defined!"
        return 1
    fi
fi

# common
BSPJOB=4
BSPROOT=$(cd $(dirname "${BASH_SOURCE[0]}") >/dev/null && pwd)

# platform
if [[ -z "$ARG" ]]; then
    BSPCC=gcc
    BSPCXX=g++
    BSPHOST=
    BSPCFLAGS=
    BSPLDFLAGS=
    BSPPLATFORM=x86_64
elif [ "ios64" == "$ARG" ]; then
    BSPCC=$(xcrun --sdk iphoneos -f clang)
    BSPCXX=$(xcrun --sdk iphoneos -f clang++)
    BSPHOST="--host=aarch64-apple-darwin"
    BSPCFLAGS="-arch arm64 -miphoneos-version-min=12.1 -isysroot $(xcrun --sdk iphoneos --show-sdk-path) -fno-common"
    BSPLDFLAGS=
    BSPPLATFORM=ios64
elif [ "iossim" == "$ARG" ]; then
    BSPCC=$(xcrun --sdk iphonesimulator -f clang)
    BSPCXX=$(xcrun --sdk iphonesimulator -f clang++)
    BSPHOST="--host=x86_64-apple-darwin"
    BSPCFLAGS="-arch x86_64 -miphonesimulator-version-min=12.1 -isysroot $(xcrun --sdk iphonesimulator --show-sdk-path)"
    BSPLDFLAGS=
    BSPPLATFORM=iossim
elif [ "android-aarch64" == "$ARG" ]; then
# export ANDROID definitions and paths
#    export ANDROID_NDK=/usr/local/android-ndk-r19b
#    export ANDROID_HOST_TAG=darwin-x86_64
    export PATH=${ANDROID_NDK}/toolchains/llvm/prebuilt/${ANDROID_NDK}/bin:$PATH
    BSPCC=aarch64-linux-android21-clang
    BSPCXX=aarch64-linux-android21-clang++
    BSPHOST="--host aarch64-linux-android"
    BSPCFLAGS=
    BSPLDFLAGS=
    BSPPLATFORM=android-aarch64
fi

# debugging & profiling
BSPEXTRAFLAGS=

# tools and output
BSPTOOLS=${BSPROOT}/tools/o
BSPROOTFS=${BSPROOT}/build/${BSPPLATFORM}
PATH=${BSPTOOLS}/bin:${PATH}

export BSPJOB BSPROOT BSPCC BSPCXX BSPHOST BSPCFLAGS BSPLDFLAGS BSPPLATFORM BSPEXTRAFLAGS BSPTOOLS BSPROOTFS PATH


# export var for Makefile.build and other Makefile's
if [[ -z "$ARG" ]]; then
    echo "export no TARGET_QUERY, autodetect!";
elif [ "ios64" == "$ARG" ]; then
    echo "export TARGET_QUERY=ios64";
    export TARGET_QUERY=ios64
elif [ "iossim" == "$ARG" ]; then
    echo "export TARGET_QUERY=iossim";
    export TARGET_QUERY=iossim
elif [ "android-aarch64" == "$ARG" ]; then
    echo "export TARGET_QUERY=android-aarch64";
    export TARGET_QUERY=android-aarch64
fi

# tools selection
export TOOLS_ENABLE_CMAKE=y

# depends selection
export DEPENDS_ENABLE_OPENSSL=y
export DEPENDS_ENABLE_CURL=y
export DEPENDS_ENABLE_LIBEVENT=y
export DEPENDS_ENABLE_LIBEVHTP=y
export DEPENDS_ENABLE_UNIVALUE=y
export DEPENDS_ENABLE_BITCOIN=y
